[env:esp32dev_downldr]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_espidf.stack_size = 16384
board_build.partitions = partitions_dualapp.csv  ; 

build_src_filter = 
    +<downloader_main.cpp>        ; C++ main
    +<simibox_download.cpp>       ; C++ download
    +<simibox_boot_manager_idf.c> ; Pure C modules
    +<simibox_wifi_creds_idf.c>   
    +<simibox_led_idf.c>