[env:esp32dev_downldr]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_espidf.stack_size = 16384
board_build.partitions = partitions_dualapp.csv

build_type = release
build_flags =
  -O2
  -DDOWNLOADER_DEV_MODE=1     ; <<< single switch
  -DTEST_FOLDER=\"mozart\"
  -DCORE_DEBUG_LEVEL=3
  -DCONFIG_FATFS_FD_MAX=20  ; Increase max file descriptors
  -DCONFIG_FATFS_MAX_FILES=20

[env:esp32dev_downldr_prod]
extends = env:esp32dev_downldr
build_flags =
  -O2
  -DDOWNLOADER_DEV_MODE=0     ; dev mode off